/* global Office */

/**
 * Opens a new compose window with filing links when server-side draft creation is unavailable.
 */
export function openFilingLinksCompose(links, emailSubject, { emailFont = "Segoe UI", fontSize = "11" } = {}) {
  if (!links || links.length === 0) return false;

  try {
    const mailbox = Office?.context?.mailbox;
    if (!mailbox?.displayNewMessageForm) {
      console.warn("[filingCompose] displayNewMessageForm not available.");
      return false;
    }

    const fontFam = emailFont || "Segoe UI";
    const fontSz = fontSize ? `${fontSize}pt` : "11pt";
    const formattedLinks = links.map((l) => `- ${l}`).join("<br/>");
    const htmlBody = `
      <div style="font-family: '${fontFam}', sans-serif; font-size: ${fontSz}; color: #323130;">
        <p>The following email has been filed to a shared location:</p>
        <p><strong>${formattedLinks}</strong></p>
        <p><i>Generated by Koyomail</i></p>
      </div>
    `;

    mailbox.displayNewMessageForm({
      toRecipients: [],
      subject: `Filed Link: ${emailSubject || "Email"}`,
      htmlBody,
    });
    return true;
  } catch (err) {
    console.warn("[filingCompose] Failed to open compose window:", err.message);
    return false;
  }
}
